# Generated by Django 6.1.1 on 2026-09-17 17:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bgg_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('num_jugadores_min', models.PositiveIntegerField()),
                ('num_jugadores_max', models.PositiveIntegerField()),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('edad_minima', models.PositiveIntegerField()),
                ('dificultad', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('link_referido', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'juego',
            },
        ),
        migrations.CreateModel(
            name='Mecanica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Mecánica',
                'verbose_name_plural': 'Mecánicas',
                'db_table': 'mecanica',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='JuegoCategoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juego_categorias', to='juegos.categoria')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juego_categorias', to='juegos.juego')),
            ],
            options={
                'db_table': 'juego_categoria',
            },
        ),
        migrations.AddField(
            model_name='juego',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='juegos', through='juegos.JuegoCategoria', to='juegos.categoria'),
        ),
        migrations.CreateModel(
            name='JuegoMecanica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juego_mecanicas', to='juegos.juego')),
                ('mecanica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juego_mecanicas', to='juegos.mecanica')),
            ],
            options={
                'db_table': 'juego_mecanica',
            },
        ),
        migrations.AddField(
            model_name='juego',
            name='mecanicas',
            field=models.ManyToManyField(blank=True, related_name='juegos', through='juegos.JuegoMecanica', to='juegos.mecanica'),
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_pedido', to='juegos.juego')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='juegos.pedido')),
            ],
            options={
                'db_table': 'linea_pedido',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMIN', 'Administrador')], default='CLIENTE', max_length=20)),
                ('idioma_preferido', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('ca', 'Catalán'), ('it', 'Italiano')], default='es', max_length=5)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_usuario',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='juegos.perfilusuario'),
        ),
        migrations.CreateModel(
            name='BibliotecaJuego',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('favorito', models.BooleanField(default=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliotecas', to='juegos.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to='juegos.perfilusuario')),
            ],
            options={
                'db_table': 'biblioteca_juego',
            },
        ),
        migrations.CreateModel(
            name='SesionSugerencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_sugerencia', models.CharField(choices=[('BIBLIOTECA', 'Biblioteca'), ('COMPRA', 'Compra')], max_length=20)),
                ('num_jugadores', models.PositiveIntegerField()),
                ('duracion_max', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('anfitrion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_sugerencia', to='juegos.perfilusuario')),
            ],
            options={
                'db_table': 'sesion_sugerencia',
            },
        ),
        migrations.CreateModel(
            name='SesionJuegoPropuesto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_propuesto', to='juegos.juego')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos_propuestos', to='juegos.sesionsugerencia')),
            ],
            options={
                'db_table': 'sesion_juego_propuesto',
            },
        ),
        migrations.CreateModel(
            name='VotoSugerencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(default=1)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='juegos.juego')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='juegos.sesionsugerencia')),
            ],
            options={
                'db_table': 'voto_sugerencia',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agregado_el', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='juegos.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='juegos.perfilusuario')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.AddConstraint(
            model_name='juegocategoria',
            constraint=models.UniqueConstraint(fields=('juego', 'categoria'), name='unique_juego_categoria'),
        ),
        migrations.AddConstraint(
            model_name='juegomecanica',
            constraint=models.UniqueConstraint(fields=('juego', 'mecanica'), name='unique_juego_mecanica'),
        ),
        migrations.AddConstraint(
            model_name='bibliotecajuego',
            constraint=models.UniqueConstraint(fields=('usuario', 'juego'), name='unique_usuario_juego_biblioteca'),
        ),
        migrations.AddConstraint(
            model_name='sesionjuegopropuesto',
            constraint=models.UniqueConstraint(fields=('sesion', 'juego'), name='unique_sesion_juego_propuesto'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('usuario', 'juego'), name='unique_usuario_juego_wishlist'),
        ),
    ]
